### ISSUE TITLE
Update stable version in repo from 0.0.0 to 1.1.0

### ISSUE THREAD

**Issue by GermanBluefox** [minukodu/ioBroker.minuaru#20]
# Think about adding version 1.1.0 to stable repository.
**Version**: stable=**0.0.0** (0 days old) => latest=**1.1.0** (99 days old)
**Installs**: stable=**0** (0%), latest=**3** (42.86%), total=**7**
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json)

**Comment by SVallant** [comment]
new stable will be, if working, version 2.0.0
