### ISSUE TITLE
Please readd package test

### ISSUE THREAD

**Issue by mcm1957** [minukodu/ioBroker.minuaru#34]
Package test has been disabled. **This test is required** so please readd it. 

If really required you cann skip linter test by setting lint:false but add a issue to track fixing linter problems as standard linter test should pass for every adapter too.

**Comment by SVallant** [comment]
Added, but error is:
`(node:1928) ESLintIgnoreWarning: The ".eslintignore" file is no longer supported. Switch to using the "ignores" property in "eslint.config.js": https://eslint.org/docs/latest/use/configure/migration-guide#ignoring-files`

How to solve this ?
There is no eslint.config.js ...

**Comment by SVallant** [comment]
added, but fails:
` ESLint couldn't find an eslint.config.(js|mjs|cjs) file.`

@mcm1957  Can you provide an example file ? Thank you

**Comment by mcm1957** [comment]
you have updated to eslint 9 i assume.
either downgrade to latest eslint 8 or add anbeslint 9 config.

at the moment i do not gave a working example. but this will come.

you can set lint:false at workfliw for now and add a reminder ossue to reactivate it later.

**Comment by SVallant** [comment]
downgraded to v8 now it works, thank you
