### ISSUE TITLE
Update stable version in repo from 0.0.0 to 1.1.0

### ISSUE THREAD

**Issue by GermanBluefox** [minukodu/ioBroker.minuaru#36]
# Think about adding version 1.1.0 to stable repository.
**Version**: stable=**0.0.0** (0 days old) => latest=**1.1.0** (583 days old)
**Installs**: stable=**0** (0%), latest=**4** (50%), total=**8**

Click to use [developer portal](https://www.iobroker.dev/adapter/minuaru/releases)
Click to [edit](https://github.com/ioBroker/ioBroker.repositories/edit/master/sources-dist-stable.json)

**Do not close this issue manually as a new issue will be created if condition for update still exists.**

Please drop a comment if any reason exists which blocks updating to version 1.1.0 at this time.

Note: This is an automatically generated message and not personally authored by bluefox!
      @mcm1957 for evidence

**Comment by mcm1957** [comment]
Is there any reason to delay adding this adapter to stable any longer?
Please drop a commit if you know any reason to refrain from adding.

**If there is no response until 16.11.2024 we could decide to add anyway**

**Comment by SVallant** [comment]
at the moment there a no additional user-tests
https://forum.iobroker.net/topic/77693/test-adapter-minuaru-2-x

**Comment by SVallant** [comment]
2.0.0 is out now, after some days i will make ist stable

https://forum.iobroker.net/topic/77693/test-adapter-minuaru-2-x?_=1732891526008&lang=de
