### ISSUE TITLE
Think about to fix the issues found by adapter checker

### ISSUE THREAD

**Issue by ioBrokerChecker** [minukodu/ioBroker.minuaru#4]
I am an automatic service that looks for possible errors in ioBroker and creates an issue for it. The link below leads directly to the test:

https://adapter-check.iobroker.in/?q=https://raw.githubusercontent.com/minukodu/ioBroker.minuaru

- [ ] [E506] "admin/jsonCustom.json" not found, but custom support is declared
- [ ] [E300] Not found on travis. Please setup travis

I have also found warnings that may be fixed if possible.

- [ ] [W400] Cannot find "minuaru" in latest repository

Thanks,
your automatic adapter checker.

P.S.: There is a community in Github, which supports the maintenance and further development of adapters. There you will find many experienced developers who are always ready to assist anyone. New developers are always welcome there. For more informations visit: https://github.com/iobroker-community-adapters/info

**Comment by SVallant** [comment]
E506: error of adapter checker: https://github.com/ioBroker/ioBroker.repochecker/issues/46
E300: move to Github Actions

**Comment by SVallant** [comment]
fixed with https://github.com/minukodu/ioBroker.minuaru/pull/15

**Comment by ioBrokerChecker** [comment]
Thanks, that all bugs have been fixed.
